### ISSUE TITLE
NoMethodError: undefined method `each' for nil

### ISSUE THREAD

**Issue by histfak** [socketry/protocol-rack#17]
I use Falcon with Sinatra and few times a day I see the following exception in the logs:

```[2024-09-08 03:21:33] {"time":"2024-09-08T03:21:33+00:00","severity":"warn","oid":8160,"pid":5,"subject":"Async::Task","annotation":"Reading HTTP/1.1 requests for Async::HTTP::Protocol::HTTP1::Server.","message":"Task may have ended with unhandled exception.","event":{"type":"failure","root":"/usr/src/app","class":"NoMethodError","message":"\u001b[1mundefined method `each' for nil (\u001b[1;4mNoMethodError\u001b[m\u001b[1m)\u001b[m\n\n\u001b[1m\t\t\t\t\t@body.each(&block)\u001b[m\n\u001b[1m\t\t\t\t\t     ^^^^^\u001b[m","backtrace":["/usr/local/bundle/ruby/3.3.0/gems/protocol-rack-0.7.0/lib/protocol/rack/body/enumerable.rb:71:in `each'","/usr/local/bundle/ruby/3.3.0/gems/protocol-http1-0.22.0/lib/protocol/http1/connection.rb:313:in `write_fixed_length_body'","/usr/local/bundle/ruby/3.3.0/gems/protocol-http1-0.22.0/lib/protocol/http1/connection.rb:401:in `write_body'","/usr/local/bundle/ruby/3.3.0/gems/async-http-0.75.0/lib/async/http/protocol/http1/server.rb:96:in `block in each'","/usr/local/bundle/ruby/3.3.0/gems/async-2.17.0/lib/async/task.rb:318:in `defer_stop'","/usr/local/bundle/ruby/3.3.0/gems/async-http-0.75.0/lib/async/http/protocol/http1/server.rb:57:in `each'","/usr/local/bundle/ruby/3.3.0/gems/async-http-0.75.0/lib/async/http/server.rb:50:in `accept'","/usr/local/bundle/ruby/3.3.0/gems/io-endpoint-0.13.1/lib/io/endpoint/wrapper.rb:182:in `block (2 levels) in accept'","/usr/local/bundle/ruby/3.3.0/gems/async-2.17.0/lib/async/task.rb:197:in `block in run'","/usr/local/bundle/ruby/3.3.0/gems/async-2.17.0/lib/async/task.rb:422:in `block in schedule'"]}}```

No sure if this is just a bad request or bug. Ruby version is 3.3.4 and YJIT is enabled globally via RUBYOPT.

Falcon configuration:

```ruby
# frozen_string_literal: true

load :rack

hostname = File.basename(__dir__)
service hostname do
  include Falcon::Environment::Rack
  count ENV.fetch('WORKERS', 1).to_i

  preload 'preload.rb'
  cache true

  endpoint do
    Async::HTTP::Endpoint.parse("http://0.0.0.0:#{ENV.fetch('PORT',
                                                            80)}").with(protocol: Async::HTTP::Protocol::HTTP11)
  end
end

**Comment by anitagraham** [comment]
I am also getting ` undefined method 'each' for nil:NilClass (NoMethodError)` occasionally while running Rspec. 
The warning doesn't affect the testing, so this is just a me-too note. 

MacOS: 15.3 (24D60)
Ruby 3.2.4
Rails 7.1.3.4
falcon (0.48.3)
rspec-core (3.13.2)
protocol, async, etc as shown in stack dump below


```
warn: Async::Task: Reading HTTP/1.1 requests for Async::HTTP::Protocol::HTTP1::Server. [oid=0x107c0] [ec=0xfb04] [pid=28006] [2025-02-10 10:11:24 +0800]
               | Task may have ended with unhandled exception.
               |   NoMethodError: undefined method `each' for nil:NilClass (NoMethodError)
               |   
               |                                        @body.each(&block)
               |                                             ^^^^^
               |   → /Users/anita/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/protocol-rack-0.11.1/lib/protocol/rack/body/enumerable.rb:71 in `each'
               |     /Users/anita/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/protocol-http1-0.28.1/lib/protocol/http1/connection.rb:468 in `write_fixed_length_body'
               |     /Users/anita/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/protocol-http1-0.28.1/lib/protocol/http1/connection.rb:582 in `write_body'
               |     /Users/anita/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/async-http-0.86.0/lib/async/http/protocol/http1/server.rb:133 in `block in each'
               |     /Users/anita/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/async-2.21.1/lib/async/task.rb:327 in `defer_stop'
               |     /Users/anita/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/async-http-0.86.0/lib/async/http/protocol/http1/server.rb:80 in `each'
               |     /Users/anita/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/async-http-0.86.0/lib/async/http/server.rb:50 in `accept'
               |     /Users/anita/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/io-endpoint-0.14.0/lib/io/endpoint/wrapper.rb:182 in `block (2 levels) in accept'
               |     /Users/anita/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/async-2.21.1/lib/async/task.rb:197 in `block in run'
               |     /Users/anita/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/async-2.21.1/lib/async/task.rb:435 in `block in schedule'

```
